# Generated by Django 4.0.6 on 2022-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_choice_target_choice_target2'),
    ]

    operations = [
        migrations.CreateModel(
            name='hey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(default=1)),
                ('target2', models.IntegerField(default=3)),
            ],
        ),
    ]
