# Generated by Django 4.0.6 on 2022-08-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_hey'),
    ]

    operations = [
        migrations.AddField(
            model_name='hey',
            name='target3',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
